### ISSUE TITLE
Sign-in links are broken

### ISSUE THREAD

**Issue by st-clair-clarke** [ggranum/revector#6]
The links at https://revectordemo.firebaseapp.com/ are broken. Cannot sign-in at all.

**Comment by ggranum** [comment]
Thanks @st-clair-clarke . I have been busy getting this projects replacement up and running. Please take a look at https://github.com/ggranum/tangential-demo. You should be able to register and sign in to that project's demo  [https://tangential-demo.firebaseapp.com](https://tangential-demo.firebaseapp.com)

Other than the admin panel there isn't much there. I need to add a nightly-reset and provide an admin account, but that might be a while :~)
